### ISSUE TITLE
GetJsonValueByKey<std::string> cannot find sublevel key

### ISSUE THREAD

**Issue by liuhuanjim013** [mujin/mujinvision#21]
for example, "detection.modulename" doesn't work, neither does "/detection/modulename"

**Comment by akovski** [comment]
how about adding a function named GetJsonValueByPointer?

**Comment by liuhuanjim013** [comment]
that'd be fine if we have it a better name and rename the original one. or make the original one support arbitrary level.

**Comment by akovski** [comment]
What's a better name?

**Comment by liuhuanjim013** [comment]
a name that suggests multilevel key won't work. such as GetJsonValueBySingleLevelKey, GetJsonValueByMultiLevelKey. or we just fix the current one and look for "." and "/" in the key to support both cases.

**Comment by rdiankov** [comment]
it's not a good idea to use the name to determine the level of the tree to look at.... having an excplicit function that can access multi level is better
